#!/bin/bash

make
rm brasd-0.1.0.tar.gz
make dist
mv brasd-0.1.0.tar.gz ../brasd_0.1.0.orig.tar.gz
rm -r .pc
rm -r debian/brasd
rm ../brasd_0.1.0-1*
debuild -kB16A1050 -S
dput ppa:zcbenz/brasd ../*.changes
